name = "grammar-review-sync"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "2081d8db42e04f12b55b1492b3f6906b"

### https://jlptn1n2mastergrammarcard.workers.dev